AllCops:
  Exclude:
    - config/unicorn.rb
    - bin/**
    - lib/tasks/sample.rake
  RunRailsCops: true

ClassLength:
  Max: 300

MethodLength:
  Max: 50

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 38

Style/GlobalVars:
  AllowedVariables: [$evm]

# supports hyphen in jellyfish-samlauth
Style/FileName:
  Enabled: false